import os
import json
from datetime import datetime, timezone
from typing import Dict, Any, Optional
from src.backend.firestore_client import get_incident_from_firestore

REPORTS_DIR = os.path.abspath("reports")

def generate_postmortem_markdown(incident_data: Dict[str, Any]) -> str:
    """Generates a complete post-mortem RCA report in markdown format."""
    inc_id = incident_data.get("incident_id", "UNKNOWN")
    title = incident_data.get("title", "Untitled Incident")
    severity = incident_data.get("severity", "SEV-2")
    primary_tech = incident_data.get("primary_technology", "Unknown")
    techs = incident_data.get("technologies", [])
    component = incident_data.get("component", "General")
    failure_mode = incident_data.get("failure_mechanism", "Service Degradation")
    domain = incident_data.get("root_cause_domain", "Infrastructure & Runtime")
    pattern = incident_data.get("resolution_pattern", "Manual Remediation")
    desc = incident_data.get("description", "No description available.")
    resolution = incident_data.get("resolution", "No resolution provided.")
    summary = incident_data.get("summary_insight", "")
    tax_path = " -> ".join(incident_data.get("taxonomy_path", []))
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    md = f"""# Post-Mortem RCA Report: {inc_id} - {title}

**Status**: Resolved | **Severity**: {severity} | **Generated**: {now}

---

## 1. Executive Summary
- **Primary Technology Affected**: {primary_tech}
- **Component Subsystem**: {component}
- **Root Cause Domain**: {domain}
- **Failure Mechanism**: {failure_mode}
- **Resolution Pattern**: {pattern}
- **Dynamic Taxonomy Path**: `{tax_path}`

### Key Takeaway
{summary if summary else "Autonomous analysis detected a " + failure_mode + " impacting " + primary_tech + "."}

---

## 2. Technical Incident Description & Impact
{desc}

- **Involved Technology Footprint**: {', '.join(techs) if techs else primary_tech}
- **Assessed Severity**: {severity}

---

## 3. Root Cause Analysis (RCA)
- **Breakdown Point**: `{component}` within `{primary_tech}`.
- **Trigger Condition**: `{failure_mode}`.
- **Engineering Classification**: `{domain}`.

---

## 4. Remediation & Action Taken
{resolution}

### Pattern Applied
`{pattern}`

---

## 5. Preventative Action Items
| Action Item | Owner | Priority | Status |
| :--- | :--- | :--- | :--- |
| Update Prometheus / Alertmanager alerting rules for {failure_mode} | SRE Team | High | To Do |
| Update standard runbook for {primary_tech} ({component}) | Platform Engineering | Medium | To Do |
| Perform capacity review and tune limits/timeouts | Service Owner | High | Done |

---
*Report autonomously generated by Incident Analyst Agent.*
"""
    return md

def create_postmortem_report(incident_id: str, output_dir: Optional[str] = None) -> Dict[str, Any]:
    """
    Fetches incident from Firestore (or local dataset fallback) and writes the post-mortem report to reports/.
    """
    out_dir = output_dir or REPORTS_DIR
    os.makedirs(out_dir, exist_ok=True)

    incident_data = get_incident_from_firestore(incident_id)

    # Fallback to local enriched incidents if not yet in Firestore
    if not incident_data:
        local_path = os.path.abspath("data/enriched_incidents.json")
        if os.path.exists(local_path):
            with open(local_path, "r") as f:
                items = json.load(f)
                for item in items:
                    inc = item.get("incident", {})
                    if inc.get("incident_id") == incident_id:
                        cls = item.get("classification", {})
                        incident_data = {
                            "incident_id": inc.get("incident_id"),
                            "title": inc.get("title"),
                            "description": inc.get("description"),
                            "resolution": inc.get("resolution"),
                            "severity": inc.get("severity"),
                            "primary_technology": cls.get("primary_technology"),
                            "technologies": cls.get("technologies"),
                            "component": cls.get("component"),
                            "failure_mechanism": cls.get("failure_mechanism"),
                            "root_cause_domain": cls.get("root_cause_domain"),
                            "resolution_pattern": cls.get("resolution_pattern"),
                            "summary_insight": cls.get("summary_insight"),
                            "taxonomy_path": item.get("taxonomy_path", [])
                        }
                        break

    if not incident_data:
        raise ValueError(f"Incident with ID '{incident_id}' could not be found in Firestore or local data.")

    report_markdown = generate_postmortem_markdown(incident_data)
    filename = f"postmortem_{incident_id.lower().replace('-', '_')}.md"
    filepath = os.path.join(out_dir, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report_markdown)

    return {
        "status": "success",
        "incident_id": incident_id,
        "filename": filename,
        "filepath": filepath,
        "markdown_content": report_markdown
    }
